# Generated by Django 3.1.2 on 2020-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='is_tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
    ]
