# Generated by Django 3.1.2 on 2020-12-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201230_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productraiting',
            options={'verbose_name': 'Product Raiting', 'verbose_name_plural': 'Product Raitings'},
        ),
        migrations.CreateModel(
            name='RetailerRaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')], max_length=1, verbose_name='Raiting')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.retailer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'verbose_name': 'Retailer Raiting',
                'verbose_name_plural': 'Retailer Raitings',
            },
        ),
    ]
